import type { Metadata } from "next";
import {Inter, Outfit } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Navbar from "./(public)/_components/Navbar";
import { ToasterProvider } from "@/components/ToasterProvider";
import { AuthProvider } from "@/context/AuthContext";
import FloatingFeedbackButton from "@/components/FloatingFeedbackButton";
import FloatingAIButton from "@/components/FloatingAIButton";

const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });


export const metadata: Metadata = {
  title: "JobMitra",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/icon/launcher_icon.ico",
        sizes: "any",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${outfit.variable}`}>
      <head>
        <link rel="icon" href="/icon/launcher_icon.png" type="image/png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz@20..48&display=block" rel="stylesheet" />
      </head>
      <body
       
      >
        <AuthProvider>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
          <ToasterProvider />
          <FloatingFeedbackButton />
          <FloatingAIButton />
          {children}
        </GoogleOAuthProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
